plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.agkontrol'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.agkontrol"
        minSdk 28
        targetSdk 28
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
